v0.1.1
KPAKEH-SP/ATM pull request #7
Opened 2023-11-19 19:22 UTC by KPAKEH-SP

-banknotePatterns заменён на enum

-giveMoney возвращает HasMap вместо массива

-изменены наименования по конвенции

-банкомат не выдаёт всю сумму, которую может, вместо этого выдаёт ошибку о нехватке средств

-банкомат выдаёт ошибку при попытке снять сумму для которой нужны банкноты, которых не существует

-ошибка о нехватке средств вылетает через checked exception

2023-11-20 16:11 UTC, difiozy requested changes

2023-11-20 16:11 UTC, difiozy commented on src/BanknoteStorage.java
> +            while (sum - banknoteValue.getBanknote() >= 0) {                                                            // Вычитает текущий проверочный номинал из указаной суммы, пока может это делат
Я так понял что по преждену при ошибке купюры исчезают

2023-11-20 18:41 UTC, KPAKEH-SP commented on src/BanknoteStorage.java
> +            while (sum - banknoteValue.getBanknote() >= 0) {                                                            // Вычитает текущий проверочный номинал из указаной суммы, пока может это делат
Нет, если выходит ошибка, то программа останавливается и сохранение хранилища не происходит

2023-11-20 18:48 UTC, KPAKEH-SP commented on src/BanknoteStorage.java
> +    public static HashMap<Integer, Integer> giveMoney(int sum) {                                                        // Возвращает массив купюр, подсчитанных из переданой суммы
Поправил в новой версии: https://github.com/KPAKEH-SP/ATM/tree/Develop

2023-11-20 20:04 UTC, difiozy commented on src/Display.java
> +            showStartMenu();
Тут получается не очень хороший момент с рекурсивным вызовом, лучше от него избавиться
Если долго делать неправильный ввод то программа завершиться с StacjkOverflow

2023-11-20 20:08 UTC, difiozy commented on src/BanknoteStorageSaver.java
> +            BanknoteStorage.availableBanknotes = (((HashMap<Integer, Integer>) ois.readObject()));
Вместо прямого присвоения лучше использовать setter. Нужно соблюдать инкапсуляцию

2023-11-20 20:10 UTC, difiozy commented on src/BanknoteStorage.java
> +            while (sum - banknoteValue.getBanknote() >= 0) {                                                            // Вычитает текущий проверочный номинал из указаной суммы, пока может это делат
Давай лучше сделаем так что программа не останавливается, а просто прекращает выдавать купюры, и запрашивает новый ввод
Лучше обойтись без рекурсии

2023-11-20 20:13 UTC, difiozy commented on src/ATM.java
>  public class ATM {
Давай немного переработаем логику там образом, что бы программа не завершалась каждый раз, а

2023-11-21 22:06 UTC, difiozy requested changes

2023-11-21 22:06 UTC, difiozy commented on src/BanknoteStorage.java
> +            BanknotePatterns banknoteValue = BanknotePatterns.valueOf(currentBanknote.name());
Эту строчку можно убрать и использовать currentBanknote

2023-11-21 22:27 UTC, difiozy requested changes

2023-11-21 22:27 UTC, difiozy commented on src/BanknoteStorage.java
> +                    if (returnBanknotes.get(banknoteValue.getBanknote()) != null) {
Постарпайся эту ветку ифов заменить на getOrDefault, что он делает можешь почитать в javaDoc
Что бы в них перейти через cntrl нажми на метод, потом если нет комментариев сверху на плашке нажми Download source

2023-11-21 22:27 UTC, difiozy commented on src/BanknoteStorage.java
> +            }
Не нужно заворачивать метод в RuntimeException, выкидывай само исключение NotEnoughMoneyException, в ином случае теряется всякий смысл

Не бойся добавить его в сигнатуру метода и обработать в том месте где ты вызываешь этот метод, это более чем нормально

2023-11-21 22:27 UTC, difiozy commented on src/ATM.java
>      public static void main(String[] args) {
Вывод выглядит хорошо, интерфейс тоже
Если ввести большое чисто, например 999999999, то окажется что в банкомате вдруг стало 0 рублей, но я вообще ничего не получил
Такого быть не должно, подумай над решением этой проблемы

2023-11-21 22:27 UTC, difiozy commented on src/Display.java
> +            getMoney();
От рекурсивного вызова стоит отказаться в пользу обычного while

2023-11-21 22:27 UTC, difiozy commented on src/BanknoteStorage.java
> +                    int newAvailableBanknoteCount = (int) availableBanknotes.get(banknoteValue.getBanknote());          // Достаёт из хранилища количество необходимых купюр
Тут можно опустить (int), либо вообще использовать Integer в качестве типа, тоже хороший вариант

2023-11-21 22:27 UTC, difiozy commented on src/BanknoteStorage.java
> +            while (sum - banknoteValue.getBanknote() >= 0) {                                                            // Вычитает текущий проверочный номинал из указаной суммы, пока может это делат
Если сумма вдруг окажется очень большой то такой подход может выполняться долго, либо если ты будешь обрабатывать ооочень много запросов это станет критично, давай откажется от подсчета каждой купюры, а будем считать сколько купюр какого номинала мы можем выдать сейчас для этой суммы, тоесть просто брать sum/currentBanknote.getBanknote, дальше просто считать каждую купюру
Таким образом получится избавиться от while(...) и улучшит читаемость кода

2023-11-27 15:52 UTC, difiozy commented on src/Display.java
> +            } catch (java.util.InputMismatchException e) {
Еще раз прочитай как работает блок catch, тут указан неправильный тип
В сигнатуре этого метода не должно уже быть исключения

2023-11-27 17:33 UTC, merged